# Site settings
title: IRONKLADD
description: > # this means to ignore newlines until "baseurl:"
  Webpage for IRONKLADD, a team of students in SUNY Oswego's Spring 2015
  CSC380.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://IRONKLADD.github.io/" # the base hostname & protocol for your site
github_username: IRONKLADD

# Build settings
markdown: kramdown
kramdown:
  default_lang: javascript
  use_coderay: true
highlighter: pygments